### ISSUE TITLE
PM Team Meeting

### ISSUE THREAD

**Issue by Yesh-2691** [smartcontractresearchforum/operations#28]

**Comment by Yesh-2691** [comment]
### Jul 26, 2022

- Context Setting > 2 Paths for now , Github and Next Steps after Proposal
- Misunderstandings on which version of docs to use. 
- How are we beginning the PM process - Where does it start. 
- Proposals - Pre PM , after Proposals - PM
- Feedback on PM Github Board
  - Ines - Good but let us not overdo. 
  - Tolu - Echoes Ines
  - Brian - Issue Life cycle and standardised epics. 
  - Eugene - 1-1 calls on Meetings/calls might become a overheads
  - Do we need personal views? - How can we achieve it?
- #### Agreement 
    - PM - PM conversations go under meeting calls.
    - Proposals will live on Repo and will exist on a board view 
    - Follow agenda and notes and review for a few weeks.
- What is the difference between PM and P.Lead?
- P.Lead - Moves things forward. but definition is still fuzzy at the moment. 
- In some projects Lead and Manager will be the same.

**Comment by SirAh0** [comment]
@SirAh0 will help @Yesh-2691 form a templated google doc for project submission collaboration.

Update the issue template to provide instructions on how to create a new public dog in the google drive infrastructure.

**Comment by SirAh0** [comment]
How can we include visibility to the kinds of projects SCRF is looking for. This can lead to an issue of quality control. It's a little early in our progression to deal with this issue.

**Comment by Yesh-2691** [comment]
### Aug 19, 2022

- V1.0 Project Proposal agreed to roll out. 
- Communication on how to use the template of the Project Proposal. 
- All PM related docs to be placed in appropriate PM folder. 
- Project Proposals from all verticals should live in the same folder however it is not mandatory. Project Lead and manager to take the decision.

**Comment by Yesh-2691** [comment]
Sep 7, 2022

- The projects tracking board can be Public. 
- Make the process is culture aligned.
- Feedback about the project from the project lead and other team members,
